In [2]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from imblearn.over_sampling import RandomOverSampler


---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [3]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
customers_df = pd.read_csv(
    Path("lending_data.csv")
)

# Review the DataFrame
customers_df.head(20)

loan_size  interest_rate  borrower_income  debt_to_income  \
0     10700.0          7.672            52800        0.431818   
1      8400.0          6.692            43600        0.311927   
2      9000.0          6.963            46100        0.349241   
3     10700.0          7.664            52700        0.430740   
4     10800.0          7.698            53000        0.433962   
5     10100.0          7.438            50600        0.407115   
6     10300.0          7.490            51100        0.412916   
7      8800.0          6.857            45100        0.334812   
8      9300.0          7.096            47400        0.367089   
9      9700.0          7.248            48800        0.385246   
10     9300.0          7.085            47300        0.365751   
11     9200.0          7.015            46600        0.356223   
12     9200.0          7.043            46900        0.360341   
13     9400.0          7.101            47400        0.367089   
14     8400.0          6.703            43700        0.313501   
15     9400.0          7.136            47700        0.371069   
16     8900.0          6.897            45500        0.340659   
17     8300.0          6.648            43200        0.305556   
18     8000.0          6.539            42100        0.287411   
19    10200.0          7.460            50800        0.409449   

    num_of_accounts  derogatory_marks  total_debt  loan_status  
0                 5                 1       22800            0  
1                 3                 0       13600            0  
2                 3                 0       16100            0  
3                 5                 1       22700            0  
4                 5                 1       23000            0  
5                 4                 1       20600            0  
6                 4                 1       21100            0  
7                 3                 0       15100            0  
8                 3                 0       17400            0  
9                 4                 0       18800            0  
10                3                 0       17300            0  
11                3                 0       16600            0  
12                3                 0       16900            0  
13                3                 0       17400            0  
14                3                 0       13700            0  
15                3                 0       17700            0  
16                3                 0       15500            0  
17                2                 0       13200            0  
18                2                 0       12100            0  
19                4                 1       20800            0

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [4]:
# Separate the data into labels and features
# Separate the y variable, the labels
y = customers_df['loan_status']

# Separate the X variable, the features
X = customers_df.drop(columns=['loan_status'])

In [5]:
# Review the y variable Series
print(y)

0        0
1        0
2        0
3        0
4        0
        ..
77531    1
77532    1
77533    1
77534    1
77535    1
Name: loan_status, Length: 77536, dtype: int64


In [6]:
# Review the X variable DataFrame
X.head(20)

loan_size  interest_rate  borrower_income  debt_to_income  \
0     10700.0          7.672            52800        0.431818   
1      8400.0          6.692            43600        0.311927   
2      9000.0          6.963            46100        0.349241   
3     10700.0          7.664            52700        0.430740   
4     10800.0          7.698            53000        0.433962   
5     10100.0          7.438            50600        0.407115   
6     10300.0          7.490            51100        0.412916   
7      8800.0          6.857            45100        0.334812   
8      9300.0          7.096            47400        0.367089   
9      9700.0          7.248            48800        0.385246   
10     9300.0          7.085            47300        0.365751   
11     9200.0          7.015            46600        0.356223   
12     9200.0          7.043            46900        0.360341   
13     9400.0          7.101            47400        0.367089   
14     8400.0          6.703            43700        0.313501   
15     9400.0          7.136            47700        0.371069   
16     8900.0          6.897            45500        0.340659   
17     8300.0          6.648            43200        0.305556   
18     8000.0          6.539            42100        0.287411   
19    10200.0          7.460            50800        0.409449   

    num_of_accounts  derogatory_marks  total_debt  
0                 5                 1       22800  
1                 3                 0       13600  
2                 3                 0       16100  
3                 5                 1       22700  
4                 5                 1       23000  
5                 4                 1       20600  
6                 4                 1       21100  
7                 3                 0       15100  
8                 3                 0       17400  
9                 4                 0       18800  
10                3                 0       17300  
11                3                 0       16600  
12                3                 0       16900  
13                3                 0       17400  
14                3                 0       13700  
15                3                 0       17700  
16                3                 0       15500  
17                2                 0       13200  
18                2                 0       12100  
19                4                 1       20800

### Step 3: Check the balance of the labels variable (`y`) by using the `value_counts` function.

In [7]:
# Check the balance of our target values
y.value_counts()

0    75036
1     2500
Name: loan_status, dtype: int64

### Step 4: Split the data into training and testing datasets by using `train_test_split`.

In [8]:
# Split the data using train_test_split
# Assign a random_state of 1 to the function
X_train, X_test, y_train, y_test = train_test_split(X, y,random_state=1)

---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [9]:
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
logistic_regression_model = LogisticRegression(random_state=1)

# Fit the model using training data
lr_model = logistic_regression_model.fit(X_train, y_train)
y_train.value_counts()

0    56271
1     1881
Name: loan_status, dtype: int64

### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [10]:
# Make a prediction using the testing data
testing_predictions=lr_model.predict(X_test)

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [11]:
# Print the balanced_accuracy score of the model
score = lr_model.score(X_test, y_test)
print(score)

0.9918489475856377


In [12]:
# Generate a confusion matrix for the model
training_predictions = lr_model.predict(X_train)
training_matrix = confusion_matrix(y_train, training_predictions)
print(training_matrix)

[[55994   277]
 [  181  1700]]


In [13]:
# Print the classification report for the model
test_matrix = confusion_matrix(y_test, testing_predictions)
print(test_matrix)
training_report = classification_report(y_train, training_predictions)
print(training_report)
testing_report = classification_report(y_test, testing_predictions)
print(testing_report)


[[18663   102]
 [   56   563]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56271
           1       0.86      0.90      0.88      1881

    accuracy                           0.99     58152
   macro avg       0.93      0.95      0.94     58152
weighted avg       0.99      0.99      0.99     58152

              precision    recall  f1-score   support

           0       1.00      0.99      1.00     18765
           1       0.85      0.91      0.88       619

    accuracy                           0.99     19384
   macro avg       0.92      0.95      0.94     19384
weighted avg       0.99      0.99      0.99     19384



### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** The logistic regression model does well at predicting the healthy loans, but has low precision for high risk loan prediction.

---

## Predict a Logistic Regression Model with Resampled Training Data

### Step 1: Use the `RandomOverSampler` module from the imbalanced-learn library to resample the data. Be sure to confirm that the labels have an equal number of data points. 

In [15]:
# Instantiate the random oversampler model
# # Assign a random_state parameter of 1 to the model
oversampler_regression_model = RandomOverSampler(random_state=0)

# Fit the original training data to the random_oversampler model
X_resampled,y_resampled = oversampler_regression_model.fit_resample(X_train, y_train)

In [17]:
# Count the distinct values of the resampled labels data
y_resampled.value_counts()

0    56271
1    56271
Name: loan_status, dtype: int64

### Step 2: Use the `LogisticRegression` classifier and the resampled data to fit the model and make predictions.

In [18]:
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
logistic_regression_model_resample = LogisticRegression(random_state=1)

# Fit the model using the resampled training data
lr_model_resample = logistic_regression_model_resample.fit(X_resampled, y_resampled)

# Make a prediction using the testing data
retesting_predictions=lr_model_resample.predict(X_test)

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [19]:
# Print the balanced_accuracy score of the model 
rescore = lr_model_resample.score(X_test, y_test)
print(rescore)

0.9938093272802311


In [20]:
# Generate a confusion matrix for the model
retraining_predictions = lr_model_resample.predict(X_resampled)
retraining_matrix = confusion_matrix(y_resampled, retraining_predictions)
print(retraining_matrix)

[[55964   307]
 [  280 55991]]


In [21]:
# Print the classification report for the model
retest_matrix = confusion_matrix(y_test, retesting_predictions)
print(test_matrix)
retraining_report = classification_report(y_resampled, retraining_predictions)
print(training_report)
retesting_report = classification_report(y_test, retesting_predictions)
print(retesting_report)

[[18663   102]
 [   56   563]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56271
           1       0.86      0.90      0.88      1881

    accuracy                           0.99     58152
   macro avg       0.93      0.95      0.94     58152
weighted avg       0.99      0.99      0.99     58152

              precision    recall  f1-score   support

           0       1.00      0.99      1.00     18765
           1       0.84      0.99      0.91       619

    accuracy                           0.99     19384
   macro avg       0.92      0.99      0.95     19384
weighted avg       0.99      0.99      0.99     19384



### Step 4: Answer the following question

**Question:** How well does the logistic regression model, fit with oversampled data, predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** The logistic regression model, fit with the oversampled data, predicted the healthy and high risk loans well. The oversampled data fit increased the unhealthy loan recall. 